/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface StencilFirstComponent {
    }
    interface StencilPropComponent {
        "name": string;
    }
}
declare global {
    interface HTMLStencilFirstComponentElement extends Components.StencilFirstComponent, HTMLStencilElement {
    }
    var HTMLStencilFirstComponentElement: {
        prototype: HTMLStencilFirstComponentElement;
        new (): HTMLStencilFirstComponentElement;
    };
    interface HTMLStencilPropComponentElement extends Components.StencilPropComponent, HTMLStencilElement {
    }
    var HTMLStencilPropComponentElement: {
        prototype: HTMLStencilPropComponentElement;
        new (): HTMLStencilPropComponentElement;
    };
    interface HTMLElementTagNameMap {
        "stencil-first-component": HTMLStencilFirstComponentElement;
        "stencil-prop-component": HTMLStencilPropComponentElement;
    }
}
declare namespace LocalJSX {
    interface StencilFirstComponent {
    }
    interface StencilPropComponent {
        "name"?: string;
    }
    interface IntrinsicElements {
        "stencil-first-component": StencilFirstComponent;
        "stencil-prop-component": StencilPropComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "stencil-first-component": LocalJSX.StencilFirstComponent & JSXBase.HTMLAttributes<HTMLStencilFirstComponentElement>;
            "stencil-prop-component": LocalJSX.StencilPropComponent & JSXBase.HTMLAttributes<HTMLStencilPropComponentElement>;
        }
    }
}
