/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./../components/app/AppFooter/index.vue')['default']
    AppFooterItem: typeof import('./../components/app/AppFooter/AppFooterItem.vue')['default']
    AppHeading: typeof import('./../components/app/AppHeading/index.vue')['default']
    BaseLayout: typeof import('./../components/app/BaseLayout.vue')['default']
    CarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    DemoCard: typeof import('./../components/app/DemoCard/index.vue')['default']
    IonLogoStencil: typeof import('~icons/ion/logo-stencil')['default']
    LogosWebcomponents: typeof import('~icons/logos/webcomponents')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Starport: typeof import('vue-starport')['Starport']
    StarportCarrier: typeof import('vue-starport')['StarportCarrier']
    TwemojiFlagBrazil: typeof import('~icons/twemoji/flag-brazil')['default']
  }
}
